Feature/03 homepage
mouradof/instamint pull request #16
Opened 2024-05-16 01:05 UTC by Siiddy

2024-05-18 20:25 UTC, lchaufournais requested changes

2024-05-18 20:25 UTC, lchaufournais commented on eslint.config.mjs
Need to delete this file.

2024-05-18 20:25 UTC, lchaufournais commented on jsconfig.json
Why it's empty ?

2024-05-18 20:25 UTC, lchaufournais commented on public/images/Instamint.png
Use bucket

2024-05-18 20:25 UTC, lchaufournais commented on public/images/mint.png
Use bucket

2024-05-18 20:25 UTC, lchaufournais commented on public/images/mintSolid.png
Use bucket

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/index.js
> +    origin: "*",
Last correction from Avetis said that we can't allow all.

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/LikeRoute.js
> +const prepareRoutesLike = ({ app, db }) => {
Why use db ?

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/LikeRoute.js
> +      const existingLike = await db.table("likes").where({ postId, userId }).first()
Use your model

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/LikeRoute.js
> +      const likeCount = await db.table("likes").where({ postId }).count("* as likeCount")
Use your model

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/LikeRoute.js
> +    const existingLike = await db.table("likes").where({ postId, userId }).first()
Use your model

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/LikeRoute.js
> +    const existingLike = await db.table("likes").where({ postId, userId }).first()
Use Your model

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/LikeRoute.js
> +    await db.table("likes").where({ postId, userId }).delete()
Use your model

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/LikeRoute.js
> +      c.status(500)
Last correction said that we can't use magic number to declare our error code.

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/LikeRoute.js
> +      c.status(500)
Last correction said that we can't use magic number to declare our error code.

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/LikeRoute.js
> +      c.status(404)
Last correction said that we can't use magic number to declare our error code.

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/SubscribedRoute.js
> +          c.status(400)
Last correction said that we can't use magic number to declare our error code.

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/SubscribedRoute.js
> +          c.status(404)
Last correction said that we can't use magic number to declare our error code.

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/SubscribedRoute.js
> +          c.status(404)
Last correction said that we can't use magic number to declare our error code.

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/SubscribedRoute.js
> +          c.status(404)
Last correction said that we can't use magic number to declare our error code.

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/SubscribedRoute.js
> +        c.status(200)
Last correction said that we can't use magic number to declare our http code.

2024-05-18 20:25 UTC, lchaufournais commented on src/api-post/src/routes/posts/SubscribedRoute.js
> +        c.status(500)
Last correction said that we can't use magic number to declare our error code.

2024-05-18 20:25 UTC, lchaufournais commented on src/app/components/business/FeedPost.jsx
> +          ;[apiError, apiData] = await getSubscribedPost({ userId: session.id, page })
Syntax error

2024-05-18 20:25 UTC, lchaufournais commented on src/app/components/business/FeedPost.jsx
> +          ;[apiError, apiData] = await getForyouPost({ userId: session.id, page })
Syntax error

2024-05-18 20:25 UTC, lchaufournais commented on src/app/hooks/usePostInteractions.jsx
I don't really get why you do this but why not

2024-05-19 19:46 UTC, merged

2024-06-02 19:08 UTC, avetisk commented on src/pages/home/index.jsx
> +  // } = useAppContext()
Dead code!

Remove it.

2024-06-02 19:08 UTC, avetisk commented on src/app/styles/Home.module.css
> +  animation: spin 3s infinite linear;
Use tailwind, not plain CSS.

2024-06-02 19:08 UTC, avetisk commented on src/app/services/posts/likesPostGet.mjs
> +    postId = parseInt(postId)
You shouldn't need to do it here.

2024-06-02 19:09 UTC, avetisk commented on src/app/hooks/usePostInteractions.jsx
> +  }, [postId, isLiked, deleteLikePost, postLikePost, session.id])
Early returns are missing~!