add delete post functionality, update errors file and news feed type …
mouradof/instamint pull request #35
Opened 2024-05-23 22:52 UTC by Siiddy

add delete post functionality, update errors file and news feed type conversation in locale storage.

2024-05-27 07:40 UTC, lchaufournais requested changes

2024-05-27 07:40 UTC, lchaufournais commented on src/app/components/business/DeleteModalPost.jsx
> +            </div>
use component Toast

2024-05-27 23:23 UTC, merged

2024-07-08 16:06 UTC, avetisk commented on src/api-post/src/routes/posts/DeletePostRoute.js
> +}
Helpers~!

2024-07-08 16:07 UTC, avetisk commented on src/app/components/business/DeleteModalPost.jsx
> +      }, 2000)
Store the duration in a config file and use it everywhere you need such duration.

Would make your app much more homogenous.

2024-07-08 16:07 UTC, avetisk commented on src/pages/home/index.jsx
>    // } = useAppContext()
Dead code 😱